services:
  nginx:
    container_name: nginx
    image: nginx:1.27.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/growin/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/growin/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/growin/data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - growin-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /home/ubuntu/growin/data/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/growin/data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    networks:
      - growin-network

networks:
  growin-network:
    external: true