services:
  growin-api-green:
    image: ghcr.io/growin-2025/growin-server:latest
    container_name: growin-api-green
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - growin-network

networks:
  growin-network:
    external: true